
sqlite_db:
  name: results.db
  folder: results
  tables:
    solutions:
      name: solutions
      fields:
        - {name: id,         type: INTEGER PRIMARY KEY}
        - {name: dip_dir,    type: real}
        - {name: dip_ang,    type: real}
        - {name: stereoplot, type: blob}
        - {name: creat_time, type: DATE}
        - {name: modif_time, type: DATE}
    src_pts:
      name: src_points
      fields:
        - {name: id,         type: INTEGER PRIMARY KEY}
        - {name: id_sol,     type: INTEGER}
        - {name: x,          type: real}
        - {name: y,          type: real}
        - {name: z,          type: real}