
sqlite_db:
  tables:
    solutions:
      name: solutions
      fields:
        - id:         {name: id,         type: INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL}
        - dip_dir:    {name: dip_dir,    type: REAL NOT NULL}
        - dip_ang:    {name: dip_ang,    type: REAL NOT NULL}
        - label:      {name: label,      type: TEXT}
        - comments:   {name: comments,   type: TEXT}
        - creat_time: {name: creat_time, type: DATE NOT NULL}

    src_pts:
      name: src_points
      fields:
        - id:         {name: id,         type: INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL}
        - id_sol:     {name: id_sol,     type: INTEGER NOT NULL}
        - x:          {name: x,          type: REAL NOT NULL}
        - y:          {name: y,          type: REAL NOT NULL}
        - z:          {name: z,          type: REAL NOT NULL}
