
sqlite_db:
  name: results.db
  folder: results
  tables:
    solutions:
      name: solutions
      fields:
        - id:         {name: id,         type: INTEGER PRIMARY KEY}
        - dip_dir:    {name: dip_dir,    type: real}
        - dip_ang:    {name: dip_ang,    type: real}
        - creat_time: {name: creat_time, type: DATE}
        - modif_time: {name: modif_time, type: DATE}
    src_pts:
      name: src_points
      fields:
        - id:         {name: id,         type: INTEGER PRIMARY KEY}
        - id_sol:     {name: id_sol,     type: INTEGER}
        - x:          {name: x,          type: real}
        - y:          {name: y,          type: real}
        - z:          {name: z,          type: real}
